In [31]:
import torch
from torch import Tensor
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
import pandas as pd
import os

In [35]:
def create_df(loc, names):
    
    L = []
    for name in names:
        fp = os.path.join(loc, name + ".csv")
        df = pd.read_csv(fp)
        L.append(df)
    df0 = pd.concat(L)
    return df0

def create_numpys(df):
    L = []
    for i in range(10):
        L.append('year{}_citation_count'.format(i))
    data0 = df[L].to_numpy(dtype=np.float32)
    data  = np.expand_dims(data0, axis=-1)
    labels = df['citationCount'].to_numpy(dtype=np.float32)
    data_size = len(labels)
    
    train_data, rest_data = torch.utils.data.random_split(data, [int(data_size/data_size),data_size - int(data_size/data_size)])
    train_labels, rest_labels = torch.utils.data.random_split(labels, [int(data_size/data_size),data_size - int(data_size/data_size)])
    rest_data_size = len(rest_labels)
    
    valid_data, rest_data2 = torch.utils.data.random_split(rest_data, [int(rest_data_size/rest_data_size),rest_data_size - int(rest_data_size/rest_data_size)])
    valid_labels, rest_labels2 = torch.utils.data.random_split(rest_labels, [int(rest_data_size/rest_data_size),rest_data_size - int(rest_data_size/rest_data_size)])
    rest_data_size2 = len(rest_labels2)
    
    test_data, rest_data2 = torch.utils.data.random_split(rest_data2, [int(rest_data_size2/rest_data_size2),rest_data_size2 - int(rest_data_size2/rest_data_size2)])
    test_labels, rest_labels2 = torch.utils.data.random_split(rest_labels2, [int(rest_data_size2/rest_data_size2),rest_data_size2 - int(rest_data_size2/rest_data_size2)])
    
    np.save('../CitationByYearData/processed3/trainx.npy', train_data)
    np.save('../CitationByYearData/processed3/trainy.npy', train_labels)
    np.save('../CitationByYearData/processed3/validx.npy', valid_data)
    np.save('../CitationByYearData/processed3/validy.npy', valid_labels)
    np.save('../CitationByYearData/processed3/testx.npy', test_data)
    np.save('../CitationByYearData/processed3/testy.npy', test_labels)
        

In [36]:
loc_str = r"C:\Users\shrey\Documents\Box Sync\Stanford_academics\2021-2022\Fall Quarter\CS 229\Project\Academic_Influence_Prediction-main\CitationByYearData"
names = ["data1", "data2", "data3"]
DataF = create_df(loc_str, names)
DataF.describe()

year  referenceCount  citationCount  influentialCitationCount  \
count  5246.000000     5246.000000    5246.000000               5246.000000   
mean   1992.618567       62.997713    4138.074724                270.745902   
std      16.842430      137.282876    6934.185798                651.693982   
min    1848.000000        0.000000       0.000000                  0.000000   
25%    1985.000000        0.000000    1588.000000                 60.000000   
50%    1997.000000       23.000000    2656.500000                136.000000   
75%    2005.000000       66.000000    4414.000000                264.000000   
max    2009.000000     2060.000000  199652.000000              18088.000000   

       year0_citation_count  year1_citation_count  year2_citation_count  \
count           5246.000000           5246.000000           5246.000000   
mean              11.040412             28.172703             44.896683   
std               30.449982             52.183681             75.404025   
min                0.000000              0.000000              0.000000   
25%                0.000000              2.000000              4.000000   
50%                2.000000             10.000000             19.000000   
75%                8.000000             32.000000             55.000000   
max              421.000000            585.000000           1257.000000   

       year3_citation_count  year4_citation_count  year5_citation_count  \
count           5246.000000           5246.000000           5246.000000   
mean              59.235799             72.206634             84.088448   
std              101.650399            120.745970            132.680310   
min                0.000000              0.000000              0.000000   
25%                6.000000              8.000000             10.000000   
50%               26.000000             34.000000             41.000000   
75%               73.000000             90.000000            105.000000   
max             1588.000000           2150.000000           1625.000000   

       year6_citation_count  year7_citation_count  year8_citation_count  \
count           5246.000000           5246.000000           5246.000000   
mean              96.120854            105.468547            114.156881   
std              151.381095            159.539161            166.298684   
min                0.000000              0.000000              0.000000   
25%               12.000000             13.000000             16.000000   
50%               49.000000             56.000000             62.000000   
75%              120.000000            134.000000            147.000000   
max             2040.000000           2152.000000           1667.000000   

       year9_citation_count  
count           5246.000000  
mean             123.594739  
std              181.799737  
min                0.000000  
25%               17.000000  
50%               68.000000  
75%              156.000000  
max             2032.000000

In [37]:
create_numpys(DataF)

In [38]:
loc_str2 = r"C:\Users\shrey\Documents\Box Sync\Stanford_academics\2021-2022\Fall Quarter\CS 229\Project\Academic_Influence_Prediction-main\CitationByYearData"

# training dataset
a = np.load(os.path.join(loc_str, r'processed3\trainx.npy'))
b = np.load(os.path.join(loc_str, r'processed3\trainy.npy'))
print(a.shape, b.shape)
print(a,b)

(1, 10, 1) (1,)
[[[ 9.]
  [32.]
  [63.]
  [69.]
  [68.]
  [74.]
  [79.]
  [88.]
  [87.]
  [70.]]] [3982.]


In [41]:
# validation dataset
a = np.load(os.path.join(loc_str, r'processed3\validx.npy'))
b = np.load(os.path.join(loc_str, r'processed3\validy.npy'))
print(a.shape, b.shape)
print(a,b)

(1, 10, 1) (1,)
[[[ 10.]
  [ 15.]
  [ 23.]
  [ 34.]
  [ 77.]
  [ 68.]
  [ 87.]
  [110.]
  [106.]
  [ 97.]]] [1780.]


In [44]:
# test dataset
a = np.load(os.path.join(loc_str, r'processed3\testx.npy'))
b = np.load(os.path.join(loc_str, r'processed3\testy.npy'))
print(a.shape, b.shape)
print(a,b)

(1, 10, 1) (1,)
[[[  6.]
  [ 39.]
  [ 50.]
  [ 78.]
  [ 96.]
  [141.]
  [217.]
  [279.]
  [280.]
  [326.]]] [1868.]
